name: naglec
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

# Залежності додатку
dependencies:
  media_kit: ^1.1.10
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4 # Для підтримки кодеків, включаючи webm
  video_player: ^2.8.1
  flutter:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8
  get_it: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  window_manager: ^0.4.3
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/npcs/mom/video/
    - lib/assets/
    #- lib/assets/npcs/mom/kitchen.jpg  # Або просто папку:
    - lib/assets/npcs/mom/
    - lib/assets/GG.png
    - lib/assets/home_gg/rooms/
    - lib/assets/home_gg.jpg
    - lib/assets/left_panel/
    - lib/assets/home_gg/rooms/room_yard.jpg
